### PR TITLE
Add User update API

### PR DESCRIPTION
**Pull request by darcywong00**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languagedepot-api/7)

### CODE REVIEW

**Comment by irahopkinson** [comment]
*[src/api/UserController.php, line 134 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-Kknh4J0XHjM4wBbKuX4:-Kknh4J0XHjM4wBbKuX5:b-gpogzv) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L134)):*
> ```PHP
>         $user = User::findByLogin($login);
>         if ($user == null)
>         {
> ```

belongs on the if line above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7)*

**Comment by irahopkinson** [comment]
*[src/api/UserController.php, line 140 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-KknhDrEAPWvDZXCkBhk:-KknhDrEAPWvDZXCkBhl:b-gpogzv) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L140)):*
> ```PHP
>         // If mail is different, check that it is unique
>         if (($user->mail != $mail) && (User::findByMail($mail) != null))
>         {
> ```

belongs on the if line above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7)*

**Comment by irahopkinson** [comment]
*[src/api/UserController.php, line 167 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-Kknjp3oEaF5B5Nnp2jg:-Kknjp3oEaF5B5Nnp2jh:b-mijgik) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L167)):*
> ```PHP
>             // $fail[] = $asArray;
>             throw new \Exception("Cannot encode to json");
>         } else {
> ```

don't need the else. The if is an exception check that exits with a throw. Normal flow of code follows with whats currently in the else; i.e put the body of the else after the whole if structure and remove else part.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7)*

**Comment by irahopkinson** [comment]
*[src/api/UserController.php, line 152 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-KknkUlKne6aPiw_7jjV:-KknkUlKne6aPiw_7jjW:bxz8je8) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L152)):*
> ```PHP
>                 'language',
>                 'mail']));
> ```

Would read a bit nicer if these to blank lines where removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7)*

**Comment by irahopkinson** [comment]
*[src/api/UserController.php, line 147 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-Kknief5ggTxjrfnmnaO:-Kknief5ggTxjrfnmnaP:by4mpvg) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L147)):*
> ```PHP
>         $attributes = array_intersect_key(
>             $request->request->all(),
>             array_flip([
> ```

be consistent with your style for array definitions; use array() or [] consistently. We can use [] on PHP 5.4+ which would be my preference because its shorter and clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7)*

**Comment by megahirt** [comment]
Looks fine to me.  I assume the tests pass.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/api/UserController.php, line 147 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-Kknief5ggTxjrfnmnaO:-Kko396ZoDwCLHWDk_e6:b-jsufs8) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L147)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

be consistent with your style for array definitions; use array() or [] consistently. We can use [] on PHP 5.4+ which would be my preference because its shorter and clearer.
</blockquote></details>

+1 for being consistent.  I have used array() in the past but [ ] is good with me too since we are over PHP 5.4.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-:-Kko4ZBkUyCMi39Tly8c:b-2cxlqg)*

**Comment by darcywong00** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/api/UserController.php, line 134 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-Kknh4J0XHjM4wBbKuX4:-KlIAKrIIvIWzHxFtBQe:b-896fix) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L134)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

belongs on the if line above
</blockquote></details>

Done.

---

*[src/api/UserController.php, line 140 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-KknhDrEAPWvDZXCkBhk:-KlIALjKy-vC3kc5uJpY:b-896fix) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L140)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

belongs on the if line above
</blockquote></details>

Done.

---

*[src/api/UserController.php, line 147 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-Kknief5ggTxjrfnmnaO:-KlIAMdtCx7jphCjm6qU:b-896fix) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L147)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

+1 for being consistent.  I have used array() in the past but [ ] is good with me too since we are over PHP 5.4.
</blockquote></details>

Done.

---

*[src/api/UserController.php, line 152 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-KknkUlKne6aPiw_7jjV:-KlIANOJ8tQ3PfeJH1TC:b-896fix) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L152)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Would read a bit nicer if these to blank lines where removed.
</blockquote></details>

Done.

---

*[src/api/UserController.php, line 167 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-Kknjp3oEaF5B5Nnp2jg:-KlIAOljtdXIQnI0LbOm:b-896fix) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/85c17499ecdd31b535420c4bcb5263a1921ee533/src/api/UserController.php#L167)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

don't need the else. The if is an exception check that exits with a throw. Normal flow of code follows with whats currently in the else; i.e put the body of the else after the whole if structure and remove else part.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7)*

**Comment by megahirt** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/7#-:-KlIINiUw8K5UPHbsL3U:bnfp4nl)*

**Pull request merged**
