### PR TITLE
Add create API

### PR DESCRIPTION
**Pull request by darcywong00**
Add API call to create user from mail and plainPassword.

Additional cleanup:
-remove unused gulp-uglify
-remove unneeded utf8_encode of project name in UserController
-change api/user to api/users

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-languagedepot-api/6)

### CODE REVIEW

**Comment by megahirt** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/api/UserController.php, line 52 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-KkJzm5LPLQnBzK4GNMy:-KkJzm5LPLQnBzK4GNMz:bun9tfj) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/af10bef302a6ba37a73765305c08bd515aa7317a/src/api/UserController.php#L52)):*
> ```PHP
>             $o = new \stdclass;
>             $o->identifier = $project->identifier;
>             $o->name = utf8_encode($project->name);
> ```

I remember that you got this working without using utf8_encode since you changed the database connection or something, but I don't see that change.  Where is the utf8 fix again?

---

*[src/api/Models/User.php, line 22 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-KkK-e00f7ZxY2QTsBUT:-KkK-e00f7ZxY2QTsBUU:b-1zufk7) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/1c60c2214a750997e30435ec6ad0ae5379e41a83/src/api/Models/User.php#L22)):*
> ```PHP
>     static public function findByLogin($login)
>     {
>         return self::first(array('conditions' => array('login = ?', $login)));
> ```

strtolower($login) here ?

---

*[src/api/Models/User.php, line 32 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-KkK-Yj0HjOPjSjSiQrP:-KkK-Yj0HjOPjSjSiQrQ:b-7zr3ha) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/1c60c2214a750997e30435ec6ad0ae5379e41a83/src/api/Models/User.php#L32)):*
> ```PHP
>     static public function findByMail($mail)
>     {
>         return self::first(array('conditions' => array('mail = ?', $mail)));
> ```

don't you need a `strtolower($mail)` here ?  where does the string get lower-cased otherwise?

---

*[test/php/api/UserControllerTest.php, line 32 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-KkK04yb4I0qHy8LnR1j:-KkK04yb4I0qHy8LnR1k:b-ra3go4) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/1c60c2214a750997e30435ec6ad0ae5379e41a83/test/php/api/UserControllerTest.php#L32)):*
> ```PHP
>     }
> 
>     public function testUsernameIsAvailable_LowerUsernameExist_False() {
> ```

glad to see this test.  I couldn't figure out how it's passing without the strtolower() referenced above though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6)*

**Comment by megahirt** [comment]
a few comments/questions.  Thank you for doing this!

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-:-KkK0bJ9fBLstMQ_2xJn:b3rmicc)*

**Comment by darcywong00** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/api/UserController.php, line 52 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-KkJzm5LPLQnBzK4GNMy:-KkK1M4qyAmtMWlcU5uW:b9lv4kw) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/af10bef302a6ba37a73765305c08bd515aa7317a/src/api/UserController.php#L52)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

I remember that you got this working without using utf8_encode since you changed the database connection or something, but I don't see that change.  Where is the utf8 fix again?
</blockquote></details>

In index.php
```
        'public' => 'mysql://' . DB_USER . ':' . DB_PASS . '@localhost/languagedepot;charset=utf8',
        'private' => 'mysql://' . DB_USER . ':' . DB_PASS . '@localhost/languagedepotpvt;charset=utf8'
```

---

*[src/api/UserController.php, line 83 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-KkK4Tg0rIMrchq8rHu9:-KkK4Tg0rIMrchq8rHuA:bmc59r0) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/1c60c2214a750997e30435ec6ad0ae5379e41a83/src/api/UserController.php#L83)):*
> ```PHP
>     {
>         // Check for unique login and mail
>         $mail = $request->get('mail');
> ```

your other comments reminded me that we should standardize new users to lowercased emails.  I'll add this in another commit along with a test

---

*[src/api/Models/User.php, line 22 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-KkK-e00f7ZxY2QTsBUT:-KkK4f41MuVRcpV9lTe2:bpbifu0) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/1c60c2214a750997e30435ec6ad0ae5379e41a83/src/api/Models/User.php#L22)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

strtolower($login) here ?
</blockquote></details>

The mysql queries seem to be case-insensitive.

---

*[src/api/Models/User.php, line 32 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-KkK-Yj0HjOPjSjSiQrP:-KkK4n-ntmAEeqlwdru6:b-7ropln) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/1c60c2214a750997e30435ec6ad0ae5379e41a83/src/api/Models/User.php#L32)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

don't you need a `strtolower($mail)` here ?  where does the string get lower-cased otherwise?
</blockquote></details>

ditto

---

*[test/php/api/UserControllerTest.php, line 32 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-KkK04yb4I0qHy8LnR1j:-KkK23feOo6ewHuEu4R9:b-62d627) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/1c60c2214a750997e30435ec6ad0ae5379e41a83/test/php/api/UserControllerTest.php#L32)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

glad to see this test.  I couldn't figure out how it's passing without the strtolower() referenced above though.
</blockquote></details>

ah, I think mysql queries are case-insensitive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6)*

**Comment by darcywong00** [comment]
Added another commit to address lowercase

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-:-KkK6PlftQC5NC43oQwF:b-z2rz6h)*

**Comment by megahirt** [comment]
:lgtm:

---

Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/api/Models/User.php, line 22 at r1](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-KkK-e00f7ZxY2QTsBUT:-KkKGuC2qG6qBwl25fju:b-v319h2) ([raw file](https://github.com/sillsdev/web-languagedepot-api/blob/1c60c2214a750997e30435ec6ad0ae5379e41a83/src/api/Models/User.php#L22)):*
<details><summary><i>Previously, darcywong00 (Darcy Wong) wrote…</i></summary><blockquote>

The mysql queries seem to be case-insensitive.
</blockquote></details>

wow you're right.  I didn't realize they were for simple selects.   More info here:  http://stackoverflow.com/questions/3936967/mysql-case-insensitive-select

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6#-:-KkKHNZE8KLDIMW1WkQf:bnfp4nl)*

**Comment by megahirt** [comment]
Reviewed 1 of 4 files at r2.
Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6)*

**Comment by megahirt** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/web-languagedepot-api/6)*

**Pull request merged**
